export const ANNOUNCEMENT_TITLE_MAX_LENGTH = 255;
export const ANNOUNCEMENT_BODY_MAX_LENGTH = 5000;
export const ANNOUNCEMENT_SEARCH_MAX_LENGTH = 255;

export const ANNOUNCEMENT_PAGE_SIZE_DEFAULT = 10;
export const ANNOUNCEMENT_PAGE_SIZE_MAX = 100;

export const PUBLICATION_DATE_DISPLAY_FORMAT = 'MM/DD/YYYY HH:mm';
